# Generated by Django 3.0.7 on 2020-06-08 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0002_auto_20200608_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='quote_source',
            field=models.CharField(default='unknown', max_length=128),
        ),
    ]
