# Generated by Django 3.0.7 on 2020-06-12 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0003_auto_20200608_0414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='quote_source',
            new_name='source',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='quote_body',
        ),
        migrations.AddField(
            model_name='quote',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
