# Generated by Django 3.0.7 on 2020-06-12 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0004_auto_20200612_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='body',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
