# Generated by Django 4.1.2 on 2022-10-08 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0005_auto_20200612_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='source',
            field=models.CharField(default='anonymous', max_length=128),
        ),
    ]
