version: '3.6'

services:
  db:
    container_name: quotable_db
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
        - postgres_data:/var/lib/postgresql/data
  web:
    container_name: quotable
    environment:
      - DB_NAME=$DB_NAME
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - PHOTOS_S3_BUCKET=${PHOTOS_S3_BUCKET}
    build: .
    command: bash -c "echo \"import sys; from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.create_superuser('admin', 'admin@myproject.com', 'password') if len(User.objects.all()) < 1 else print('admin already created'); sys.exit(0)\" | python manage.py shell &&
     python manage.py collectstatic --no-input &&
     python manage.py migrate && 
     python manage.py runserver 0.0.0.0:80"
    volumes:
      - .:/code
    ports:
      - "80:80"
    depends_on:
      - db
volumes:
  postgres_data: